require File.join(File.dirname(__FILE__), "aws-deploy/credentials")
require File.join(File.dirname(__FILE__), "aws-deploy/load_balance")
require File.join(File.dirname(__FILE__), "aws-deploy/maintenance")
require File.join(File.dirname(__FILE__), "aws-deploy/instance")
require File.join(File.dirname(__FILE__), "aws-deploy/workers")